# src/rag/models.py — v1
"""RAG retrieval models: SearchResult, RAGContext, RetrievalPlan, CorpusContext.

See spec §26 for full documentation.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from ayextractor.consolidator.models import CNode, TNode, XEdge


class SearchResult(BaseModel):
    """Single result from a vector or graph store query."""

    source_type: Literal[
        "chunk", "entity_profile", "relation_profile", "community_summary"
    ]
    source_id: str
    content: str
    score: float
    metadata: dict[str, Any] = Field(default_factory=dict)


class CorpusContext(BaseModel):
    """Cross-document knowledge retrieved from Corpus Graph."""

    cnodes: list[CNode] = Field(default_factory=list)
    tnodes: list[TNode] = Field(default_factory=list)
    xedges: list[XEdge] = Field(default_factory=list)
    source_document_count: int = 0


class RAGContext(BaseModel):
    """Assembled RAG context injected into agent prompts during enrichment."""

    assembled_text: str
    community_summaries: list[str] = Field(default_factory=list)
    entity_profiles: list[str] = Field(default_factory=list)
    chunk_excerpts: list[str] = Field(default_factory=list)
    corpus_context: CorpusContext | None = None
    contradictions: list[str] = Field(default_factory=list)
    total_token_count: int = 0
    search_results: list[SearchResult] = Field(default_factory=list)


class RetrievalPlan(BaseModel):
    """Plan generated by query_classifier for orchestrating retrieval levels."""

    query_type: Literal["conceptual", "factual", "relational", "exploratory"]
    levels_to_query: list[
        Literal["community", "entity", "chunk", "corpus"]
    ] = Field(default_factory=list)
    estimated_token_cost: int = 0
